trigger: none   # You can change to 'main' or any branch later

pool:
  name: Default   # Your self-hosted Mac agent pool name

steps:
# 1️⃣  Clean previous test data
- script: |
    rm -rf allure-results allure-report
  displayName: "Clean previous Allure data"

# 2️⃣  Check connected Android device
- script: |
    echo "Checking connected devices..."
    adb devices
  displayName: "Verify Android device connection"

# 3️⃣  Start Appium server in background
- script: |
    echo "Starting Appium server..."
    nohup appium --log-level info > appium.log 2>&1 &
    sleep 10
    echo "Appium server started successfully"
  displayName: "Start Appium server"

# 4️⃣  Run pytest automation tests
- script: |
    echo "Running Appium tests..."
    pytest Test_cases/test_serach_hotel.py --alluredir=allure-results
  displayName: "Run pytest Appium tests"

# 5️⃣  Generate Allure report
- script: |
    echo "Generating Allure report..."
    allure generate allure-results --clean -o allure-report
  displayName: "Generate Allure report"

# 6️⃣  Publish Allure report directly in Azure DevOps (UI tab)
- task: PublishHtmlReport@1
  displayName: "Publish Allure HTML Report"
  inputs:
    reportDir: 'allure-report'
    tabName: 'Allure Report'
    reportName: 'Appium Test Results'
